name: "Build container image"

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: "⬇ Checkout"
      uses: actions/checkout@v2
    - name: "🐳 Set up Docker Buildx"
      uses: docker/setup-buildx-action@v1
    - name: "🐳 Login to GHCR"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: foosel
        password: ${{ secrets.PAT }}
    - name: "🏗 Build"
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./src
        repository: OctoPrint/CustoPiZer
        push: true
        tags: |
          ghcr.io/octoprint/custopizer:latest
